spring.application.name=tarea3adt
spring.main.allow-circular-references=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/circo_damianqm?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.batch.job.enabled=false

usuarioAdmin=admin
passwordAdmin=admin

# ObjectDB en modo embebido (fichero local, no requiere servidor)
objectdb.url=objectdb:db/circo_incidencias.odb
objectdb.username=admin
objectdb.password=admin
